artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: 
  source_local_url: C:/Users/US593/Work/Datasets/Deep-Coccidiosis-Detection.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion